spring:
# Banco maquina Jeudi
#    datasource.url: jdbc:postgresql://db.jeudi.dev:5432/market-db
#    datasource.username: market-app
#    datasource.password: 1123

# Banco Clound obs.: so libera uma coneção por vez
    datasource.url: jdbc:postgresql://tuffi.db.elephantsql.com:5432/fefxzoja
    datasource.username: fefxzoja
    datasource.password: smoJuLyk2d3_2sF7LD3365gg0nbdlG8v

# Banco Local
#    datasource.url: jdbc:postgresql://localhost:5432/market-db
#    datasource.username: postgres
#    datasource.password: 123
    jpa.hibernate.ddl-auto: update
    jpa.show-sql: true
    jpa.properties.hibernate.format_sql: true
    jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
    jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect

jwt:
    secret: SequenciaDeCaracteresParaAssinarToken
    expiration: 600000

logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
spring.http.log-request-details: true
