spring:
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create
            format_sql: false
            temp:
            use_jdbc_metadata_defaults: false
    datasource:
        url: jdbc:postgresql://market-place-db-postgres/market-db
        username: postgres
        password: 123

# Banco Clound obs.: so libera uma coneção por vez
#url: jdbc:postgresql://tuffi.db.elephantsql.com:5432/fefxzoja
#    username: fefxzoja
#    password: smoJuLyk2d3_2sF7LD3365gg0nbdlG8v

## Banco Local Postgres
#        url: jdbc:postgresql://localhost:5432/market-db
#        username: postgres
#        password: 123
# Banco maquina Jeudi
#        url: jdbc:postgresql://db.jeudi.dev:5432/market-db
#        username: market-app
#        password: 1123


jwt:
    secret: SequenciaDeCaracteresParaAssinarToken
    expiration: 60000

#logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
#spring.http.log-request-details: true
